# This file is used to test the mailu/setup utility
# Deployment files can be found on github.com/mailu/infra


services:
  redis:
    image: redis:alpine

  setup:
    image: ${DOCKER_ORG:-localhost/mailu}/setup:${MAILU_VERSION:-local}
    env_file: .env
    depends_on:
      - redis
    ports:
      - 127.0.0.1:8001:8001
